steps:
  - name: 'golang:1.11.1-stretch'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/sinmetal/go2storage/$BRANCH_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/go2storage-node
      - go2storage-node=gcr.io/$PROJECT_ID/sinmetal/go2storage/$BRANCH_NAME:$COMMIT_SHA
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=private-cluster'
images: ['gcr.io/$PROJECT_ID/sinmetal/go2storage/$BRANCH_NAME:$COMMIT_SHA']